### ISSUE TITLE
Failed to resolve url or custom specifier.

### ISSUE THREAD

**Issue by oakkim** [mischnic/parcel-resolver-root#1]
### Error
Error occurred when resolving url or custom specifier.

```
@parcel/core: Failed to resolve 'https://fonts.googleapis.com/css?family=Noto+Serif+KR|Ubuntu+Mono&display=swap' from './app/assets/scss/article.scss'

  /home/{REPOSITORY}/app/assets/scss/article.scss:1:9
  > 1 | @import url('https://fonts.googleapis.com/css?family=Noto+Serif+KR|Ubuntu+Mono&display=swap');
  >   |         ^
    2 | 
    3 | #main-container {

```

### Possible solution
Filter url or custom specifier type at index.js:34.

```javascript
    // -------------------- MODIFIED --------------------
    let invalidateOnFileCreate = [],
      invalidateOnFileChange = [];
    if (dependency.resolveFrom && dependency.specifierType != "url" && dependency.specifierType != "custom") {
      let result = await load(options, dependency.resolveFrom, options.inputFS);
      let { rewrites } = result;
      ({ invalidateOnFileCreate, invalidateOnFileChange } = result);

```

Maybe It could be a problem of wrong parcel usage. But I solved it with that solution.

**Comment by oakkim** [comment]
The solution that i suggested was so wrong. The real solution was changing order of resolvers in .parcelrc file. 

From
```json
{
    "extends": "@parcel/config-default",
    "resolvers": ["@mischnic/parcel-resolver-root", "..."]
}
```

To
```json
{
    "extends": "@parcel/config-default",
    "resolvers": ["...", "@mischnic/parcel-resolver-root"]
}
```

But it is still curious that why it's happening. Here is the log that i've got.
```
@mischnic/parcel-resolver-root: Error code: StringExpected
@mischnic/parcel-resolver-root: Error message: 
@mischnic/parcel-resolver-root: Error stack: Error
at resolveConfig (/home/{USER}/{REPOSITORY}/node_modules/@parcel/utils/lib/config.js:77:21)
at loadConfig (/home/{USER}/{REPOSITORY}/node_modules/@parcel/utils/lib/config.js:90:26)
at load (/home/{USER}/{REPOSITORY}/node_modules/@mischnic/parcel-resolver-root/index.js:111:22)
at Object.resolve (/home/{USER}/{REPOSITORY}/node_modules/@mischnic/parcel-resolver-root/index.js:40:28)
at ResolverRunner.resolve (/home/{USER}/{REPOSITORY}/node_modules/@parcel/core/lib/requests/PathRequest.js:207:44)
at async Object.run (/home/{USER}/{REPOSITORY}/node_modules/@parcel/core/lib/requests/PathRequest.js:104:16)
at async RequestTracker.runRequest (/home/{USER}/{REPOSITORY}/node_modules/@parcel/core/lib/RequestTracker.js:721:20)
at async AssetGraphBuilder.runPathRequest
(/home/{USER}/{REPOSITORY}/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:762:18)
at async PromiseQueue.runFn (/home/{USER}/{REPOSITORY}/nodemodules/@parcel/utils/lib/PromiseQueue.js:88:7)
at async PromiseQueue.next (/home/{USER}/{REPOSITORY}/nodemodules/@parcel/utils/lib/PromiseQueue.js:75:5)
```
