### ISSUE TITLE
Failed to resolve '@parcel/transformer-js/src/esmodule-helpers.js'

### ISSUE THREAD

**Issue by joebeachjoebeach** [mischnic/parcel-resolver-root#2]
Hi there.

When installing this in a local project (with parcel@2.3.1) and configuring it as documented, I get the following:
```
$ yarn start
yarn run v1.22.17
$ parcel src/index.js
Server running at http://localhost:1234
🚨 Build failed.

@parcel/core: Failed to resolve '@parcel/transformer-js/src/esmodule-helpers.js' from
'./node_modules/@parcel/transformer-js/lib/JSTransformer.js'

@mischnic/parcel-resolver-root:
```

To see if I was doing something wrong, I cloned this repo, ran `yarn install` and tried to start up the `example`, and got the same error:

```
$ git clone https://github.com/mischnic/parcel-resolver-root.git
$ cd parcel-resolver-root
$ yarn install
$ cd example
$ yarn start
yarn run v1.22.17
$ parcel src/index.js
Server running at http://localhost:1234
🚨 Build failed.

@parcel/core: Failed to resolve '@parcel/transformer-js/src/esmodule-helpers.js' from
'./node_modules/@parcel/transformer-js/lib/JSTransformer.js'

@mischnic/parcel-resolver-root:

  Error
  at resolveConfig
  (/Users/joe/code/projects/parcel-resolver-root/node_modules/@parcel/utils/lib/config.js:77:21)
  at loadConfig (/Users/joe/code/projects/parcel-resolver-root/node_modules/@parcel/utils/lib/config.js:90:26)
  at load (/Users/joe/code/projects/parcel-resolver-root/parcel-resolver-root/index.js:99:22)
  at Object.resolve (/Users/joe/code/projects/parcel-resolver-root/parcel-resolver-root/index.js:35:26)
  at ResolverRunner.resolve
  (/Users/joe/code/projects/parcel-resolver-root/node_modules/@parcel/core/lib/requests/PathRequest.js:207:44)
  at async Object.run
  (/Users/joe/code/projects/parcel-resolver-root/node_modules/@parcel/core/lib/requests/PathRequest.js:104:16)
  at async RequestTracker.runRequest
  (/Users/joe/code/projects/parcel-resolver-root/node_modules/@parcel/core/lib/RequestTracker.js:721:20)
  at async AssetGraphBuilder.runPathRequest
  (/Users/joe/code/projects/parcel-resolver-root/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:762:18)
  at async PromiseQueue._runFn
  (/Users/joe/code/projects/parcel-resolver-root/node_modules/@parcel/utils/lib/PromiseQueue.js:88:7)
  at async PromiseQueue._next
  (/Users/joe/code/projects/parcel-resolver-root/node_modules/@parcel/utils/lib/PromiseQueue.js:75:5)
```

**Comment by mischnic** [comment]
Fixed in https://github.com/mischnic/parcel-resolver-root/commit/7528bd14fbfd39b192f27adc5fb4cd0b757eeba6
